import type { ClientResponse, DateRange } from "@/lib/creativeos-types";

interface PageHeaderProps {
  /** Tab title shown on the plain (portfolio) header. */
  tabTitle: string;
  window: DateRange;
  /** When set, the pink client header is rendered instead of the plain one. */
  selectedClient?: ClientResponse["account"] | null;
}

const fmtRange = (w: DateRange) => {
  const f = (iso: string) =>
    new Date(iso + "T00:00:00").toLocaleString("en-US", { month: "short", day: "numeric" });
  return `${f(w.start)} – ${f(w.end)}`;
};

/**
 * Plain header on the portfolio view; the pink/gradient client header
 * ONLY when a specific client is selected (per spec).
 */
export function PageHeader({ tabTitle, window, selectedClient }: PageHeaderProps) {
  if (!selectedClient) {
    return (
      <div className="px-6 lg:px-8 pt-6 pb-4 border-b border-slate-200 bg-white/60">
        <div className="flex items-center gap-3">
          <div className="h-px w-8 bg-indigo-500" />
          <h1 className="cos-display text-2xl font-semibold text-slate-900">{tabTitle}</h1>
        </div>
        <p className="text-xs text-slate-500 mt-1 ml-11">
          {fmtRange(window)} · All active clients · pulled live from Google Ads
        </p>
      </div>
    );
  }

  const name = selectedClient.name.replace(/\.com$/, "");
  const meta: [string, string][] = [
    ["Report period", fmtRange(window)],
    ["Window", "Live · Video + Demand Gen"],
    ["Account ID", selectedClient.customerId],
    ["Generated by", "Ad-Lab Tooling"],
  ];

  return (
    <div className="cos-client-header relative overflow-hidden px-6 lg:px-8 pt-7 pb-5 text-white" data-testid="cos-pink-header">
      <div
        className="absolute inset-0 opacity-10 pointer-events-none"
        style={{
          backgroundImage:
            "linear-gradient(#fff 1px,transparent 1px),linear-gradient(90deg,#fff 1px,transparent 1px)",
          backgroundSize: "32px 32px",
        }}
      />
      <div className="relative flex flex-col md:flex-row md:items-end md:justify-between gap-4">
        <div>
          <div className="text-[9px] tracking-[0.12em] uppercase font-bold text-white/80 mb-2">
            Ad-Lab.io · CreativeOS
          </div>
          <h1 className="cos-display text-4xl font-bold tracking-tight">
            {name}
            <span className="text-white/50 font-light">.com</span>
          </h1>
          <div className="flex flex-wrap gap-x-6 gap-y-2 mt-4">
            {meta.map(([k, v]) => (
              <div key={k}>
                <p className="text-[9px] uppercase tracking-wider font-bold text-white/60 mb-0.5">{k}</p>
                <p className="text-xs font-semibold">{v}</p>
              </div>
            ))}
          </div>
        </div>
        <span className="inline-flex items-center gap-1.5 bg-white/16 px-2.5 py-1 rounded-full text-[11px] font-semibold self-start">
          <span className="w-1.5 h-1.5 rounded-full bg-white cos-pulse" /> Live
        </span>
      </div>
    </div>
  );
}
